config/routes.rb
Rails.application.routes.draw do

  root to: 'site#index'

  resources :users
  resources :records
  resources :trackers
  resources :feedbacks

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base

  validates :sender_name, :sender_email, :comment, presence: true
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :tracker
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  belongs_to :user
  has_many :records

  LOCATION_FROM = [
    ["Kuala Lumpur (KUL)", "KUL"]
  ]

  LOCATION_TO = [
    ["Seoul (ICN)", "ICN"]
  ]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trackers, dependent: :destroy

  accepts_nested_attributes_for :trackers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
    @feedback = Feedback.new
  end

  def create
    feedback = Feedback.new(feedback_params)

    if feedback.save
      redirect_to feedbacks_path, notice: "We heard your voice. We appreciate your feedback."
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:sender_name, :sender_email, :comment)
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:lowest, :highest, :tracker_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  end

  private

  def form_params

  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: [:show, :edit, :update, :destroy]

  # GET /trackers
  # GET /trackers.json
  def index
    @trackers = Tracker.all
  end

  # GET /trackers/1
  # GET /trackers/1.json
  def show
  end

  # GET /trackers/new
  def new
    @tracker = Tracker.new
  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = Tracker.new(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to @tracker, notice: 'Tracker was successfully created.' }
        format.json { render :show, status: :created, location: @tracker }
      else
        format.html { render :new }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to @tracker, notice: 'Tracker was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to trackers_url, notice: 'Tracker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_params
      params.require(:tracker).permit(:origin, :destination, :from_date, :to_date, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    found = User.find_by_email(params[:email])
    if found.present?
      redirect_to root_path, alert: "Sorry, the service now only support 1 tracker per email."
    else
      new_user = User.new(email: params[:email])

      if new_user.save
        tracker = Tracker.new
        tracker.origin = params[:origin]
        tracker.destination = params[:destination]
        tracker.from_date = params[:from]
        tracker.to_date = params[:to]
        tracker.target = params[:target]
        new_user.trackers << tracker

        if new_user.save
          # ScrapingJob.new.async.perform(tracker.id)
          # ScrapingJob.new.perform
          redirect_to root_path, notice: "You will be notify when price is lower than your target. Thanks for supporting the service :)"
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'success' then "alert alert-success fade in"
    when 'notice' then "alert alert-info fade in"
    when 'alert' then "alert alert-danger fade in"
    when 'error' then "alert alert-error fade in"
    when 'warning' then "alert alert-warning fade in"
    end
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/feedbacks/index.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">

    <div class="cover-container">

      <div class="masthead clearfix">
        <div class="inner">
        <h3 class="masthead-brand"><i class="fa fa-paper-plane-o fa-lg"></i>  AirAsia Flight Ticket Tracker</h3>
          <ul class="nav masthead-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li class="active"><%= link_to 'Feedback', feedbacks_path %></li>
          </ul>
        </div>
      </div>

      <div class="inner cover">
        <h1 class="cover-heading"><i class="fa fa-usd fa-lg"></i>  <i>Feedback</i>  <i class="fa fa-usd fa-lg"></i></h1>
        <div class="panel panel-info">
          <div class="panel-body">
            <%= render partial: 'partials/controls/flash', locals: { flash: flash } %>

            <%= form_for @feedback, html: { role: 'form', class: 'form-horizontal' } do |f| %>
              <div class="form-group">
                <%= f.label :sender_name, 'Name', class: 'col-sm-4 control-label' %>
                <div class="col-sm-8">
                  <%= f.text_field :sender_name, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :sender_email, 'Email', class: 'col-sm-4 control-label' %>
                <div class="col-sm-8">
                  <%= f.email_field :sender_email, class: 'form-control', placeholder: "Your Personal Email", required: true %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :comment, 'Comment', class: 'col-sm-4 control-label' %>
                <div class="col-sm-8">
                  <%= f.text_area :comment, class: 'form-control', placeholder: "Comments", required: true %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                  <%= submit_tag 'Submit', class: 'btn btn-primary btn-block', disable_with: "Hold On..."%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="mastfoot">
        <div class="inner">
          <p>Build By <a href="http://peter.virtualspirit.me">PETER WONG [VirtualSpirit]</a></p>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/layouts/_analytics.html.erb
<script async>
  (function(i,s,o,g,r,a,m)
    {
      i['GoogleAnalyticsObject']=r;
      i[r]=i[r]|| function(){
       (i[r].q=i[r].q||[]).push(arguments)
      },i[r].l=1*new Date();
      a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];
      a.async=1;
      a.src=g;
      m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48741805-1', 'virtualspirit.me');
  ga('send', 'pageview');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flight Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>
  <%= render partial: 'layouts/analytics' %>

</body>
</html>

app/views/notify/send_notify.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!-- If you delete this meta tag, Half Life 3 will never be released. -->
<meta name="viewport" content="width=device-width" />

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>AirAsia Flight Tracker</title>

<link rel="stylesheet" type="text/css" href="stylesheets/email.css" />

</head>

<body bgcolor="#FFFFFF">

<!-- HEADER -->
<table class="head-wrap" bgcolor="#999999">
  <tr>
    <td></td>
    <td class="header container" >

        <div class="content">
        <table bgcolor="#999999">
          <tr>
            <td align="right"><h6 class="collapse">AirAsia Flight Tracker</h6></td>
          </tr>
        </table>
        </div>

    </td>
    <td></td>
  </tr>
</table><!-- /HEADER -->


<!-- BODY -->
<table class="body-wrap">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <div class="content">
      <table>
        <tr>
          <td>
            <h3>Hi friend,</h3>
            <p class="lead">Great News! The ticket fare which from <%= @tracker.origin %> to  <%= @tracker.destination %>  on <%= @tracker.from_date %> to <%= @tracker.to_date %>  is now available with the lowest price at <%= @record.lowest %> ! </p>
            <!-- Callout Panel -->
            <p class="callout">
              Faster book right now! <a href="http://booking.airasia.com/Search.aspx">AirAsia Website! &raquo;</a>
            </p><!-- /Callout Panel -->
          </td>
        </tr>
      </table>
      </div><!-- /content -->

    </td>
    <td></td>
  </tr>
</table><!-- /BODY -->

</body>
</html>

app/views/partials/controls/_flash.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lowest %><br>
    <%= f.number_field :lowest %>
  </div>
  <div class="field">
    <%= f.label :highest %><br>
    <%= f.number_field :highest %>
  </div>
  <div class="field">
    <%= f.label :tracker_id %><br>
    <%= f.number_field :tracker_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <thead>
    <tr>
      <th>Lowest</th>
      <th>Highest</th>
      <th>Tracker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.lowest %></td>
        <td><%= record.highest %></td>
        <td><%= record.tracker_id %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lowest:</strong>
  <%= @record.lowest %>
</p>

<p>
  <strong>Highest:</strong>
  <%= @record.highest %>
</p>

<p>
  <strong>Tracker:</strong>
  <%= @record.tracker_id %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/site/index.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">

    <div class="cover-container">

      <div class="masthead clearfix">
        <div class="inner">
        <h3 class="masthead-brand"><i class="fa fa-paper-plane-o fa-lg"></i>  AirAsia Flight Ticket Tracker</h3>
          <ul class="nav masthead-nav">
            <li class="active"><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Feedback', feedbacks_path %></li>
          </ul>
        </div>
      </div>

      <div class="inner cover">
      <h1 class="cover-heading"><i class="fa fa-usd fa-lg"></i>  <i>Get Lowest Price Ticket!</i>  <i class="fa fa-usd fa-lg"></i></h1>
        <div class="panel panel-info">
          <div class="panel-body">
            <%= render partial: 'partials/controls/flash', locals: { flash: flash } %>

            <%= form_tag users_path, method: :post, role: 'form', class: 'form-horizontal' do %>

              <div class="form-group">
                <%= label_tag :date, 'Choose Date', class: 'col-sm-4 control-label' %>
                <div class="col-sm-8">
                  <div class="input-daterange input-group" id="datepicker">
                    <%= text_field_tag :from, '', class: 'form-control', placeholder: "From Date", required: true %>
                    <span class="input-group-addon">to</span>
                    <%= text_field_tag :to, '', class: 'form-control', placeholder: "To Date", required: true %>
                  </div>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :origin, 'Depart', class: 'col-sm-4 control-label' %>
                <div class="col-sm-8">
                  <%= select_tag :origin, options_for_select(Tracker::LOCATION_FROM), class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :destination, 'Destination', class: 'col-sm-4 control-label' %>
                <div class="col-sm-8">
                  <%= select_tag :destination, options_for_select(Tracker::LOCATION_TO), class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :target, 'Notify When Price Below', class: 'col-sm-4 control-label' %>
                <div class="col-sm-8">
                  <%= text_field_tag :target, '', class: 'form-control', required: true %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :email, 'Email', class: 'col-sm-4 control-label' %>
                <div class="col-sm-8">
                  <%= email_field_tag :email, '', class: 'form-control', placeholder: "Your Personal Email", required: true %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                  <%= submit_tag 'Notify Me', class: 'btn btn-primary btn-block', disable_with: "Hold On..."%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="mastfoot">
        <div class="inner">
          <p>Build By <a href="http://nich.virtualspirit.me">Nicholas NG [VirtualSpirit]</a></p>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/trackers/_form.html.erb
<%= form_for(@tracker) do |f| %>
  <% if @tracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tracker.errors.count, "error") %> prohibited this tracker from being saved:</h2>

      <ul>
      <% @tracker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :from_date %><br>
    <%= f.text_field :from_date %>
  </div>
  <div class="field">
    <%= f.label :to_date %><br>
    <%= f.text_field :to_date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trackers/edit.html.erb
<h1>Editing tracker</h1>

<%= render 'form' %>

<%= link_to 'Show', @tracker %> |
<%= link_to 'Back', trackers_path %>

app/views/trackers/index.html.erb
<h1>Listing trackers</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destination</th>
      <th>From date</th>
      <th>To date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%= tracker.origin %></td>
        <td><%= tracker.destination %></td>
        <td><%= tracker.from_date %></td>
        <td><%= tracker.to_date %></td>
        <td><%= tracker.user_id %></td>
        <td><%= link_to 'Show', tracker %></td>
        <td><%= link_to 'Edit', edit_tracker_path(tracker) %></td>
        <td><%= link_to 'Destroy', tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tracker', new_tracker_path %>

app/views/trackers/new.html.erb
<h1>New tracker</h1>

<%= render 'form' %>

<%= link_to 'Back', trackers_path %>

app/views/trackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @tracker.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @tracker.destination %>
</p>

<p>
  <strong>From date:</strong>
  <%= @tracker.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @tracker.to_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @tracker.user_id %>
</p>

<%= link_to 'Edit', edit_tracker_path(@tracker) %> |
<%= link_to 'Back', trackers_path %>